image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd LaravelCrud && composer install && cp .env.example .env && php artisan migrate && php artisan serve --host=0.0.0.0 # runs during prebuild
    command: cd LaravelCrud && php artisan serve --host=0.0.0.0

