image:
  file: .gitpod.Dockerfile

tasks:
  - init: composer install && cp .env.example .env && php artisan migrate && php artisan serve --host=0.0.0.0 # runs during prebuild
    command: php artisan serve --host=0.0.0.0

